name:                tfh
version:             0.1.0.0
github:              "githubuser/tfh"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tfh#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring ^>= 0.10.12
- text ^>= 1.2.4.1
- optparse-applicative ^>= 0.15.1.0
# this is the version with the bugfix for ICU 68 compatibility
# see https://github.com/haskell/text-icu/issues/49
- text-icu == 0.55.1.0
- containers ^>= 0.6.2.1
- hashable ^>= 1.3.0.0
- unordered-containers ^>= 0.2.13.0
- safe ^>= 0.3.19
- sort ^>= 1.0.0.0
- deepseq ^>= 1.4.4.0

ghc-options:
- -O2

library:
  source-dirs: src

executables:
  tfh:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - tfh

  tfhs:
    main:                Main.hs
    source-dirs:         app-io-stream
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - tfh
    - io-streams

tests:
  tfh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tfh
