name:                tfh
version:             0.1.0.0
github:              "guy-middleton/tfh"
license:             BSD3
author:              "Guy Middleton"
copyright:           "2021 Guy Middleton"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Simple Haskell reimplementation of Tim Bray's "topfew"
description:         Please see the README on GitHub at <https://github.com/guy-middleton/tfh#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring ^>= 0.10.12
- optparse-applicative ^>= 0.15.1.0
- hashable ^>= 1.3.0.0
- unordered-containers ^>= 0.2.13.0
- safe ^>= 0.3.19
- streaming ^>= 0.2.3.0
- streaming-bytestring ^>= 0.2.0

ghc-options:
- -O2
- -funbox-strict-fields

library:
  source-dirs: src

executables:
  tfh:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - tfh
    - io-streams

tests:
  tfh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tfh
